### ISSUE TITLE
WhatsApp telegram bot

### ISSUE THREAD

**Issue by namancodes029** [416d72/oiwa#7]

**Comment by amr3k** [comment]
Can you specify more?

**Comment by aizooh** [comment]
"I find the bot helpful in saving time, but I noticed one small mistake that I think should be corrected. It doesn't provide a genuine link to open WhatsApp and chat with the number. This is what I discovered."actually, i like the bot it saves time but it has one small mistake which i think should be rectified that is it does provide a genuine link to open WhatsApp and chat the number so this is what  i found out 
![image](https://github.com/amr3k/oiwa/assets/70424402/118f7b38-aefc-46ce-bb04-ee8b9960bc16)
this is the given link which has gives this error
![image](https://github.com/amr3k/oiwa/assets/70424402/21c07dcd-b549-45f9-8cfa-7dbc95b68b79)
here is the link provided 
 https://api.whatsapp.com/send?phone=+254725519154&text=
To fix the error, simply remove the plus sign from the URL provided. This will ensure that the URL is fully functional.the syntax to correct this error is just by omitting the plus sign on the url above which will make the url fully functional
i.e https://api.whatsapp.com/send?phone=254725519154&text=
![image](https://github.com/amr3k/oiwa/assets/70424402/f74d5105-b5f2-41cd-965b-12dc15b5992a)
This is just my point of view and I am open to being corrected.just my pov. i am open for correction
