### ISSUE TITLE
DOMAIN

### ISSUE THREAD

**Issue by blackglobeco** [416d72/oiwa#8]
Hi, what should I define on DOMAIN .env?

I am using replit platform because I am not sure how can I configure BOT_TOKEN and DOMAIN on Vercel.

Please help me.

**Comment by amr3k** [comment]
Hi @Bmgpt , you can easily set the env vars on vercel by going to your project settings like https://vercel.com/user-name/project-name/settings/environment-variables

And set the variables normally.

As for how to get `DOMAIN`, you can find it in `settings` > `domains`

I never used replit before so can't help you with that, sorry
