### ISSUE TITLE
Error on Vercel Deployment

### ISSUE THREAD

**Issue by blackglobeco** [416d72/oiwa#9]
Hi,

I have deployed the forked repository on Vercel by putting in the DOMAIN and BOT_TOKEN. However, there are some errors that appeared on the deployment logs as per below. What should I do to fix these errors?

<img width="1234" alt="image" src="https://github.com/amr3k/oiwa/assets/137195478/544e7c72-94c1-4d18-9f3c-552e7b63151e">

**Comment by amr3k** [comment]
I just updated all dependencies , can you update your fork and try again?

**Comment by amr3k** [comment]
@Bmgpt I hope it's fixed by now
